name: "Build"
on:
  pull_request:
    branches:
      - main
  push:
     branches:
      - main
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: qed
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix --print-build-logs build .
      - run: cachix pin qed main result --keep-revisions 3
